require("dotenv").config();

const { PORT, HTTP_PORT, HTTPS_PORT, GRADING_SERVER, FRONT_SERVER, MONGO_database, MONGO_URL, MONGO_Query, CHAIN_ID, ACCESSKEYID, SECRET_ACCESSKEY, MINE_OWNER_NFT_SELECT, CCTOKEN_SELECT } = process.env;
const MONGO_URI = `${MONGO_URL}${MONGO_database}${MONGO_Query}`;
const ENV = { PORT, HTTP_PORT, HTTPS_PORT, GRADING_SERVER, FRONT_SERVER, MONGO_URI, MONGO_database, CHAIN_ID, ACCESSKEYID, SECRET_ACCESSKEY, MINE_OWNER_NFT_SELECT, CCTOKEN_SELECT }

export default ENV